kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/log"