apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Mi
  volumeName: volume-pv