apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Mi
  volumeName: {{ .Release.Name }}-pv